name: Install GRPC
on:
  push:
  
jobs:
  install-grpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build .         
